[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''